### ISSUE TITLE
Questions about initializing conv6

### ISSUE THREAD

**Issue by Mercurialzhang** [hubeihubei/DFL-CNN-pytorch#1]
Hi, I am recurring this paper recently, but the accuracy is about 83% on CUB, I think there is some mistakes when initializing conv6. Can you show me some details of initializing conv6, many thanks.

**Comment by hubeihubei** [comment]
I also have some mistakes on it，did you get 83% accuracy on cub.maybe we can talk on wechat ，my WeChat number is 18672762156
